# Generated by Django 6.0.6 on 2026-06-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_stage_changed_at_emailtemplate_emaillog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationrule',
            name='triggered_leads',
            field=models.ManyToManyField(blank=True, related_name='triggered_rules', to='leads.lead'),
        ),
    ]
